name: Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  ghcr:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build GHCR images
        env:
          DOCKER_REPO: ghcr.io/muffl0n/s3fs
          SOURCE_COMMIT: ${{ github.sha }}
        run: ./hooks/build
      -
        name: Push GHCR images
        env:
          DOCKER_REPO: ghcr.io/muffl0n/s3fs
          SOURCE_COMMIT: ${{ github.sha }}
        run: ./hooks/push
